### ISSUE TITLE
使用时选不了图片

### ISSUE THREAD

**Issue by lijiajunply** [Lruihao/CoverView#17]
![image](https://github.com/user-attachments/assets/0bf6186a-9b21-462f-a35b-81491e0a5652)
在使用时没有图库，选择不了图片

**Comment by Lruihao** [comment]
网络问题，图片搜索API是国外的。

**Comment by Lruihao** [comment]
> 可是我使用的是Zeabur，选择的是美国区，按理来说应该不会出现这个问题

我不知道诶，我就用国内网络都可以加载出图片。
