### ISSUE TITLE
生成的图片会出现问题

### ISSUE THREAD

**Issue by BrotherJie** [Lruihao/CoverView#27]
![cover_231316](https://github.com/user-attachments/assets/de2880ef-339e-405d-87e7-383eec9c805e)

发现更新后任何一张图片下载后都会出现布局错乱的问题

**Comment by Lruihao** [comment]
最近还没时间处理，如果有需要使用可以暂时先用历史版本的链接，[历史版本](https://cover-view-2a7nsakhg-lrh-dev.vercel.app)

**Comment by Lruihao** [comment]
已修复
